### ISSUE TITLE
How to determine the bencode module version programmatically

### ISSUE THREAD

**Issue by joachimmetz** [fuzeman/bencode.py#17]
How can I determine the bencode module version programmatically. I don't see `bencode.__version__` or `bencode.get_version()` or equiv.

1. Is there a way to determine the bencode module version programmatically? (without having to rely on an external module like pkg_resources)
2. If so how?

**Comment by fuzeman** [comment]
There is two ways to retrieve the version, either `pbr.version`, or `pkg_resources`. We can't easily add `__version__` without also requiring `pbr` at runtime (currently it is only used by `setup.py`, and isn't installed to the machine).

I considered adding `__version__` resolved through `pkg_resources`, but as it's not going to be reliable it was removed again.

**Comment by joachimmetz** [comment]
Ack, thx for looking into this.

```
__version__ = pkg_resources.get_distribution('bencode.py').version
```

I'm not 100% if that will work as desired. Since it will return the version of the module according to pkg_resources, not the version of the actual running module. If find a way for pbr to set  e.g. `__version__.py` or equiv I'll let you know.
