### ISSUE TITLE
KeyError: <type 'unicode'>

### ISSUE THREAD

**Issue by ElizarovEugene** [fuzeman/bencode.py#3]
Hello. help please with saving the torrent file
```python
r = requests.get(torrent, headers={'Host':'tracktor.in'})
bt = bencode.bdecode(r.text)
			
print bt
			
f = open(filename, 'w+')
f.write(bencode.encode(bt))
```
but i have error
KeyError: <type 'unicode'>
and I do not understand what exactly is wrong

{u'comment': u'LostFilm.TV(c)', u'info': {u'piece length': 524288, u'name': u'Van.Helsing.S02E08.rus.LostFilm.TV.avi', u'private': 1, u'pieces':'...', u'source': u'LostFilm.TV', u'length': 468131840, u'profiles': [{u'width': 720, u'vcodec': u'XVID', u'height': 400, u'acodec': u'mp3'}], u'file-duration': [2581], u'file-media': [0]}, u'encoding': u'UTF-8', u'creation date': 1512330386, u'announce-list': [[u'http://bt8.tracktor.in/tracker.php/8e8671684b46a9a7b3b9e115c58c8984/announce'], [u'http://bt99.tracktor.in/tracker.php/8e8671684b46a9a7b3b9e115c58c8984/announce']], u'created by': u'uTorrent/3310', u'announce': u'http://bt8.tracktor.in/tracker.php/8e8671684b46a9a7b3b9e115c58c8984/announce'}
Van.Helsing.S02E08.avi.torrent
Traceback (most recent call last):
  File "index.py", line 88, in <module>
    l.getRss()
  File "index.py", line 54, in getRss
    self.getSerialPage(url)
  File "index.py", line 84, in getSerialPage
    f.write(bencode.encode(bt))
  File "/Library/Python/2.7/site-packages/bencode/__init__.py", line 200, in bencode
    encode_func[type(value)](value, r)
  File "/Library/Python/2.7/site-packages/bencode/__init__.py", line 156, in encode_dict
    encode_func[type(v)](v, r)
KeyError: <type 'unicode'>

**Comment by fuzeman** [comment]
Just released v2.0.0 which includes support for unicode strings. Feel free to reopen this issue if you are still experiencing issues with the latest release.
