### ISSUE TITLE
Dict with bytes as keys?

### ISSUE THREAD

**Issue by davidgfnet** [fuzeman/bencode.py#6]
I don't get why force_decode_utf8 is set to True for key reading in decode_dict. I think it's perfectly valid to have a dict which keys are byte sequences.
In fact I've come across some files from trackers which do encode hashes as bytes to save some space and therefore fail to parse using this library.
I'd send a PR but it is pretty straightforward change

**Comment by notpeter** [comment]
Do you have an example torrent file/bencoded sequence where hash keys are byte sequences for testing/validation?

**Comment by prise6** [comment]
What about this issue ?
Here's an example from scrape response request:
`scrape_http_content = b'd5:filesd20:\x85\xbe\x94\xb1 \xbe\xcf\xb4O\x94\xf9wy\xc6\x163\xc7dv)d8:completei17e10:downloadedi111e10:incompletei0ee20:\xb3\n\xf8V\xe4\xfc\xd42\x8ap\xd4\xbd\xc2\xdcc\x15\xed\xcc\xa9%d8:completei4e10:downloadedi48e10:incompletei0eeee'
`

`files` is a dictionnary where each key is a info_hash. See [specs](https://wiki.theory.org/index.php/BitTorrentSpecification#Tracker_.27scrape.27_Convention)
